name: CI
on:
  push:
    branches:
      - main

jobs:
  behave-firefox:
    name: 'Run Tests on Mozilla Firefox'
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
        cache: 'pip'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest
      
    - name: Run Behave
      run: behave -D browser="headless firefox" debug=False

  behave-chrome:
    name: 'Run Tests on Google Chrome'
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
        cache: 'pip'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: 126
        install-chromedriver: true
      
    - name: Run Behave
      run: behave -D browser="headless chrome" debug=False
